### ISSUE TITLE
Create collections pages and functional on web client

### ISSUE THREAD

**Issue by shkvik** [ringfence-inc/ringfence-client-web#18]
Figma URL: https://www.figma.com/file/eFVPUlZDqekVc9WLHDUlV8/Ringfence-(Copy)?type=design&node-id=99-288&mode=design&t=c2ODMX0KueQ4KLWL-0

Also here you need to create a form that appears above the table of already uploaded images, or there is no date instead of the icon. We use Pictures Wall from AntDsgn to upload pictures. This all happens when we click the Add Images button. There should also be a button to close the form.

![Image](https://github.com/ringfence-inc/ringfence-client-web/assets/75574213/cf34f45f-200e-467e-ba84-c0bdcb6d7bfa)

**Comment by lp1641** [comment]
Collections Page. View the contents of the collection.
1. When we move the mouse cursor over one image we see not only its status but also checkbox and open preview buttons.
2. If we have selected one image then we see the preview button and checkbox on all other images too. Also the selected pictures are highlighted with border of primary color.
3. The picture is highlighted in primary color when we put the mouse cursor over it.
4. If we click on the picture itself we have a modal window with information about it, there will be a button for generation but we do not make it yet.
5. The state of the selected elements should be transferred between the tabular view and the grid view. This is realized easier if we have the same pagination with buttons that show the numbers of pages that we can switch.
If the grid will be loaded by scrolling and the table will switch pages by buttons, it will be different logic and it will be more difficult to realize it.
6. The table should have a fixed height depending on the number of records that can be on one page. If there should be 10 records on the page, the height should be as for 10 records even if two records are loaded, so that the height of the table is not reduced.
